name: Create Rule Issues Manually

on:
  workflow_dispatch:
    inputs:
      rule_id:
        description: 'Rule ID (e.g., RULE-123)'
        required: true
        type: string
      rule_name:
        description: 'Rule Name (e.g., Suspicious Activity Detected)'
        required: true
        type: string
      rule_description:
        description: 'Rule Description (e.g., This rule detects X behavior...)'
        required: true
        type: string

jobs:
  create-issue:
    runs-on: ubuntu-latest

    permissions:
        issues: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install GitHub CLI
        run: |
          sudo apt-get install gh

      - name: Create GitHub Issue
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ISSUE_TITLE="Rule ID: ${{ github.event.inputs.rule_id }} - ${{ github.event.inputs.rule_name }}"
          ISSUE_BODY="## Rule ID: ${{ github.event.inputs.rule_id }}\n
          **Rule Name:** ${{ github.event.inputs.rule_name }}\n
          **Description:**\n
          ${{ github.event.inputs.rule_description }}\n
          🔄 **This rule requires modification or tuning.**\n
          ### Auto-generated by GitHub Actions 🚀"
          **👀 Attention:** @krutzika, please review this issue!"

          # Check if an issue already exists for this rule ID
          EXISTING_ISSUE=$(gh issue list --search "${{ github.event.inputs.rule_name }}" --json title --jq '.[].title')

          if echo "$EXISTING_ISSUE" | grep -q "${{ github.event.inputs.rule_name }}"; then
            echo "Issue for Rule ID: ${{ github.event.inputs.rule_name }} already exists. Skipping creation."
          else
            echo "Creating new issue for Rule ID: ${{ github.event.inputs.rule_name }}"
            gh issue create \
              --title "$ISSUE_TITLE" \
              --body "$ISSUE_BODY" \
              --label "tuning"
          fi
